### ISSUE TITLE
Missing library path for libomptarget-nvptx

### ISSUE THREAD

**Issue by jmellorcrummey** [clang-ykt/clang#10]
Tools.cpp needs to add a -L library path for libomptarget-nvptx. Without it, an install in a directory that is not on the default library path can't find libomptarget-nvptx.a.

I created a patch, but (as a git neophyte) can't figure out how to create a pull request from my copy of this repository. See my commit here for the fix:

https://github.com/jmellorcrummey/clang/commit/6068431423cb9ec6f4c8682bbd628fd5098983d3

Inline text for the fix is shown below: 

// add linking against library implementing OpenMP calls on NVPTX target
+CmdArgs.push_back("-L");
+std::string library = TC.getDriver().Dir + "/../lib" CLANG_LIBDIR_SUFFIX;
+CmdArgs.push_back(Args.MakeArgString(library));
CmdArgs.push_back("-lomptarget-nvptx");

**Comment by arpith-jacob** [comment]
@jmellorcrummey I'm not sure I understand your comment.  Could you not provide the -L library path via the command line when invoking Clang?

**Comment by jmellorcrummey** [comment]
On a machine where I do not have root privileges, I installed clang in /home/johnmc/pkgs-src/clang-ykt/install. 

When linking, with the following command:

` ~/pkgs-src/clang-ykt/install/bin/clang  -v -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda main.o  -lomp -lomptarget -lstdc++ -lm -o main  -L /nvvm/libdevice -L /usr/local/cuda-8.0/lib64 -lcudart`

before my patch, nvlink (invoked by clang) is invoked as follows:

` "/usr/local/cuda-8.0/bin/nvlink" -o /tmp/main-543add.out -v -arch sm_35 -lomptarget-nvptx /tmp/main-3ea6f5-e3d02f.cubin`

Thus, nvlink is not told to look in /home/johnmc/pkgs-src/clang-ykt/install/lib for libomptarget-nvptx.a. -L library paths that I pass clang in the link phase don't get passed by clang to nvlink. If libomptarget-nvptx.a is not in a library path that is searched by nvlink, symbols that the library defines end up undefined.

Even if I could,  I should not have to manually provide a library path for clang's own lib directory, no matter where clang is installed. Clang should always tell nvlink look in its clang's lib directory.

**Comment by arpith-jacob** [comment]
This seems reasonable.  We were actually using $LIBRARY_PATH to pass this information to nvlink.  @sfantao does this look good to you?

**Comment by sfantao** [comment]
Arpith, John,

I pushed:
```
diff --git a/lib/Driver/Tools.cpp b/lib/Driver/Tools.cpp
index 059b922..b9c92fe 100644
--- a/lib/Driver/Tools.cpp
+++ b/lib/Driver/Tools.cpp
@@ -12255,6 +12255,15 @@ void NVPTX::Linker::ConstructJob(Compilation &C, const JobAction &JA,
     CmdArgs.push_back("-arch");
     CmdArgs.push_back(Args.MakeArgString(gpu_arch));
 
+    // add paths specified in LIBRARY_PATH environment variable as -L options.
+    addDirectoryList(Args, CmdArgs, "-L", "LIBRARY_PATH");
+
+    // add paths for the default clang library path.
+    SmallString<256> DefaultLibPath =
+        llvm::sys::path::parent_path(TC.getDriver().Dir);
+    llvm::sys::path::append(DefaultLibPath, "lib" CLANG_LIBDIR_SUFFIX);
+    CmdArgs.push_back(Args.MakeArgString(Twine("-L") + DefaultLibPath));
+
     // add linking against library implementing OpenMP calls on NVPTX target
     CmdArgs.push_back("-lomptarget-nvptx");
 
@@ -12304,9 +12313,6 @@ void NVPTX::Linker::ConstructJob(Compilation &C, const JobAction &JA,
 
     AddOpenMPLinkerScript(getToolChain(), C, Output, Inputs, Args, CmdArgs, JA);
 
-    // add paths specified in LIBRARY_PATH environment variable as -L options
-    addDirectoryList(Args, CmdArgs, "-L", "LIBRARY_PATH");
-
     const char *Exec =
         Args.MakeArgString(getToolChain().GetProgramPath("nvlink"));
     C.addCommand(llvm::make_unique<Command>(JA, *this, Exec, CmdArgs, Inputs));
```
It should solve the issue. It will be posted on the repository once it passes all existing tests.
