### ISSUE TITLE
Compiler nvlink with OpenMP 4.5  compute capability

### ISSUE THREAD

**Issue by alessioderango** [clang-ykt/clang#11]
Hello,

I'm using OpenMP 4.5 for my studies.  I have a GTX 1050Ti with compute capability 6.0, so I compiled clang with -DLIBOMPTARGET_NVPTX_COMPUTE_CAPABILITY="60" option but when I tried to compile some program, the compiler gave me some errors with nvlink like "undefined reference to ". I noticed that when clang compiles the code with OpenMP 4.5 every time It uses sm_35 as option on my system. For example:

 "/usr/local/cuda-8.0/bin/ptxas" -m64 -O0 -v --gpu-name sm_35 --output-file /tmp/example-8e43ff.o /tmp/example-59dff9.s -c

 "/usr/local/cuda-8.0/bin/nvlink" -o /tmp/example-68b3cf.out -v -arch sm_35 -L. -L/usr/local/cuda/lib64 -L/usr/local/cuda/nvvm/libdevice -L/usr/local/lib -L/usr/local/lib -lomptarget-nvptx /tmp/example-8e43ff-8010d4.cubin

So I went inside the code and I found a workaround. In clang-ykt-llvm_trunk/tools/clang/lib/Driver/Tools.cpp:12135 the variable gpu_arch_names was always sm_35 in my case, so I just assigned to each variables gpu_arch_names the string "sm_60" and the program compiled without errors and It works fine. 
Why didn't the compiler understand the right compute capability to use?

**Comment by carlobertolli** [comment]
Hi

Thanks for reporting this. If I remember correctly, the LIBOMPTARGET_NVPTX_COMPUTE_CAPABILITY was disabled a while ago.
As this is obviously an issue, we are producing patches to the trunk to enable device target selection using a command line option. However, we are not going to propagate this to clang-ykt and your solution seems the best approach so far.

Thanks!

**Comment by carlobertolli** [comment]
Here is a reference to what I mentioned in my previous comment:

https://reviews.llvm.org/D29660

**Comment by alessioderango** [comment]
Thank you Carlo. This is very helpful!
