### ISSUE TITLE
unable to compile openmp-4.x code with clang

### ISSUE THREAD

**Issue by babouFomb** [clang-ykt/clang#13]
Hello,

My ubuntu version is 14.04, gc/g++ 4.8.
I followed these steps to install clang on an x87 machine with an NVIDIA  GeForce GT 745M GPU.

> git clone https://github.com/clang-ykt/llvm.git 
cd llvm/tools
git clone https://github.com/clang-ykt/clang.git
cd ../projects
git clone https://github.com/clang-ykt/openmp.git 
git clone https://github.com/clang-ykt/compiler-rt.git 

After run cmake with the following command: `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/rokiatou/newForge/llvm/install ..`, then `make -j8` and `make install`

Compilation and installation worked fine and I verified in my install/lib dit that: `libomptarget-nvptx.a, libomptarget.rtl.cuda.so, libomptarget.rtl.x86_64.so, libomptarget.so, libomp.so` are present.

But when I tried to compile an example c++ code with opemp 4.5 directives, with this flag: `clang++ main.cpp -I$LIBOMP_LIB -L$LIBOMP_LIB -fopenmp=libomp -omptargets=nvptx64sm_30-nvidia-linux -g -O3 -v -ferror-limit=100 -ffp-contract=fast -save-temps -o test` ; `LIBOMP_LIB` is setting  to `/home/rokiatou/newForge/llvm/install/lib`; I get the following linker error:

> /home/rokiatou/Documents/Thèse/Etat-de-lart-algo-de-bench/bilateral-filter/open_mp/src/main.cpp:239: undefined reference to `__kmpc_push_target_tripcount'
/home/rokiatou/Documents/Thèse/Etat-de-lart-algo-de-bench/bilateral-filter/open_mp/src/main.cpp:239: undefined reference to `__kmpc_push_target_tripcount'
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)

With the -v option, looking at the console, I noticed that Clang uses no time my flag `-omptargets=nvptx64sm_30-nvidia-linux`. But there is no warning about the pragma omp, so I assume that this is not a syntax problem.

For what reason does not happen to compile my program, is it my installation of Clang that is not good?

Thanks.

**Comment by arpith-jacob** [comment]
Hi,
Could you try using the flag -fopenmp-targets=nvptx64-nvidia-cuda

Here are the flags that I use:
export OMP_CFLAGS='-O3 -ffast-math -ffp-contract=fast  -fopenmp -fopenmp-nonaliased-maps  -fopenmp-targets=nvptx64-nvidia-cuda'
export OMP_LDFLAGS='-O3 -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda'

__kmpc_push_target_tripcount should be defined in libomptarget, see:
https://github.com/clang-ykt/openmp/blob/019e6c71637f3d82fe9dc47e499b6cfb78995747/libomptarget/exports

Have you updated from the git repo in the last week or so?

Regards,
Arpith

**Comment by babouFomb** [comment]
I updated from git today even just 2 hours ago. 

Thank you, I used the flags 
export OMP_CFLAGS='-O3 -ffast-math -ffp-contract=fast -fopenmp -fopenmp-nonaliased-maps -fopenmp-targets=nvptx64-nvidia-cuda'
export OMP_LDFLAGS='-O3 -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda'

It solves the linker problem.  But when I run `nvprof` in order to profile my program, I get this output:

> ==1782== Profiling application: ./test ../../../dataset/urban1_left.pgm
==1782== Profiling result:
No kernels were profiled.

==1782== API calls:
Time(%)      Time     Calls       Avg       Min       Max  Name
 56.19%  56.318ms         1  56.318ms  56.318ms  56.318ms  cuCtxCreate
 42.92%  43.017ms         1  43.017ms  43.017ms  43.017ms  cuCtxDestroy
  0.32%  324.11us        83  3.9040us     131ns  145.53us  cuDeviceGetAttribute
  0.31%  308.61us         1  308.61us  308.61us  308.61us  cudaGetDeviceProperties
  0.11%  110.04us         1  110.04us  110.04us  110.04us  cuDeviceTotalMem
  0.11%  105.25us         1  105.25us  105.25us  105.25us  cuModuleLoadDataEx
  0.04%  40.082us         1  40.082us  40.082us  40.082us  cuDeviceGetName
  0.00%  1.9720us         3     657ns     354ns  1.2300us  cuDeviceGet
  0.00%  1.4340us         3     478ns     226ns     933ns  cuDeviceGetCount
  0.00%     924ns         1     924ns     924ns     924ns  cuCtxSetCurrent
  0.00%     692ns         1     692ns     692ns     692ns  cuDriverGetVersion
  0.00%     674ns         1     674ns     674ns     674ns  cuInit

And that's pretty problematic when you want to do performance evaluation.

I see that `--gpu-name sm_35` flag is passed to `ptxas`; `-arch sm_35` to `nvlink`  and clang uses `-mlink-cuda-bitcode /usr/local/cuda-8.0/nvvm/libdevice/libdevice.compute_35.10.bc -target-feature +ptx42 -target-cpu sm_35` during the generation of assembly code. 

My GPU compute capability is sm_30, would there be a way to pass a flag to clang to specify the target GPU compute capability?

I tried with `--cuda-gpu-arch sm_30`, but I got this error message:

> clang-4.0: error: unsupported option '--cuda-gpu-arch'
clang version 4.0.0 (https://github.com/clang-ykt/clang.git dea3657f6df1c942e9d3bc510c0eef81b9bbd477) (https://github.com/clang-ykt/llvm.git 6e30986ed8fb8cb9b32c0b379fe46d17403ec954)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/rokiatou/newForge/llvm/install/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.2.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.2.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda-8.0, version 8.0
clang-4.0: error: no such file or directory: 'sm_30'
clang-4.0: warning: Expect degraded performance on the target device due to missing libomptarget-nvptx.bc in library path. [-Wopenmp-target]

Thanks.

**Comment by arpith-jacob** [comment]
Try passing the following options to cmake when configuring Clang/llvm:

-DCMAKE_C_FLAGS="'-DOPENMP_NVPTX_COMPUTE_CAPABILITY=30'" -DCMAKE_CXX_FLAGS="'-DOPENMP_NVPTX_COMPUTE_CAPABILITY=30'" -DLIBOMPTARGET_NVPTX_COMPUTE_CAPABILITY=30

**Comment by babouFomb** [comment]
Thank you, I passed the options 

> -DCMAKE_C_FLAGS="'-DOPENMP_NVPTX_COMPUTE_CAPABILITY=30'" -DCMAKE_CXX_FLAGS="'-DOPENMP_NVPTX_COMPUTE_CAPABILITY=30'" -DLIBOMPTARGET_NVPTX_COMPUTE_CAPABILITY=30

To cmake and recompiling `Clang/llvm`.  This solved the problem, now clang pass `sm_30` to `ptxas` and `nvlink`.
