### ISSUE TITLE
Target task with dependencies 

### ISSUE THREAD

**Issue by hyviquel** [clang-ykt/clang#19]
Hi all,

When I try to compile an application using target task with dependencies like  `#pragma omp target map(...) dep(...) nowait`, I got the following error from clang:
```
/tmp/test-0be526.o: In function `main':
/tmp/test-c55779.bc:(.text+0xb8): undefined reference to `__kmpc_omp_target_task_alloc'
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
```
Asynchronous target construct does not yet support clauses of dependencies? 
In fact, I found the commit c31f0a602da42b124567e069aa6dc6ed39c10bd4 about it but did not find the corresponding kmpc function in the openmp runtime, but maybe I'm missing something 😉.

Thanks!

**Comment by arpith-jacob** [comment]
I believe the runtime doesn't yet have support for asynchronous target tasks.  @gr409 feel free to correct me.  Contributions are welcome!

**Comment by gr409** [comment]
> I believe the runtime doesn't yet have support for asynchronous target tasks. @gr409 feel free to correct me. Contributions are welcome!

Correct, libomptarget does not support async target tasks, so the corresponding runtime API functions have not been implemented (e.g. `kmpc_omp_target_task_alloc`). Support is currently only at the compiler level.
