### ISSUE TITLE
Offloading to Nvidia Kepler GPU

### ISSUE THREAD

**Issue by siddharth19** [clang-ykt/clang#22]
clang -O3 -fopenmp=libomp -fopenmp-targets=nvptx64-nvidia-linux -o saxpy saxpy.c
Used this command to compile the code. Got the error:

nvlink error   : Undefined reference to '__kmpc_kernel_parallel' in '/tmp/saxpy-0c5610.cubin'
nvlink error   : Undefined reference to '__kmpc_kernel_end_parallel' in '/tmp/saxpy-0c5610.cubin'
nvlink error   : Undefined reference to '__kmpc_kernel_init' in '/tmp/saxpy-0c5610.cubin'
nvlink error   : Undefined reference to '__kmpc_kernel_deinit' in '/tmp/saxpy-0c5610.cubin'
/usr/bin/ld: cannot find /tmp/saxpy-97687a.out
/usr/bin/ld: cannot find /tmp/saxpy-97687a.out
clang-6.0: error: fatbinary command failed with exit code 255 (use -v to see invocation)
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)

Searching for it I realised this is due to difference in architecture(Using Kepler GPU).
Used this cmake command:
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=../../install -DLLVM_ENABLE_BACKTRACES=ON -DLLVM_ENABLE_WERROR=OFF -DBUILD_SHARED_LIBS=OFF -DLLVM_ENABLE_RTTI=ON -DOPENMP_ENABLE_LIBOMPTARGET=ON -DCMAKE_C_FLAGS='-DOPENMP_NVPTX_COMPUTE_CAPABILITY=20' -DCMAKE_CXX_FLAGS='-DOPENMP_NVPTX_COMPUTE_CAPABILITY=20' -DLIBOMPTARGET_NVPTX_COMPUTE_CAPABILITY=20 -DCLANG_OPENMP_NVPTX_DEFAULT_ARCH=sm_20 -DLIBOMPTARGET_NVPTX_ENABLE_BCLIB=true -G "Unix Makefiles" ../

**BUT when using cmake I got this message:**
CMake Warning at tools/clang/CMakeLists.txt:251 (message):
  Resetting default architecture for OpenMP offloading to Nvidia GPUs to
  sm_35

CMake Warning:
  Manually-specified variables were not used by the project:

    LIBOMPTARGET_NVPTX_COMPUTE_CAPABILITY
    LIBOMPTARGET_NVPTX_ENABLE_BCLIB

Why is this??

**Comment by gr409** [comment]
Compute capability 2.0 is not supported. The minimum required is 3.5, hence the warning about resetting to 3.5. Do you have a sm_35 Kepler?

**Comment by siddharth19** [comment]
A sm_20 Kepler

**Comment by siddharth19** [comment]
I have a Tesla K20Xm which has a compute capability of 3.5.
