### ISSUE TITLE
segmentation fault in GPU

### ISSUE THREAD

**Issue by mnakao** [clang-ykt/clang#23]
I use cuda-9.1 and Tesla K20Xm. I compiled clang-ykt as following command.

> $ cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/home/mnakao/work/clang-ykt -DLLVM_ENABLE_BACKTRACES=ON -DLLVM_ENABLE_WERROR=OFF -DBUILD_SHARED_LIBS=OFF -DLLVM_ENABLE_RTTI=ON -DOPENMP_ENABLE_LIBOMPTARGET=ON -DCMAKE_C_FLAGS='-DOPENMP_NVPTX_COMPUTE_CAPABILITY=35' -DCMAKE_CXX_FLAGS='-DOPENMP_NVPTX_COMPUTE_CAPABILITY=35' -DLIBOMPTARGET_NVPTX_COMPUTE_CAPABILITY=35 -DCLANG_OPENMP_NVPTX_DEFAULT_ARCH=sm_35  -DLIBOMPTARGET_NVPTX_ENABLE_BCLIB=true -G Ninja ../sources/llvm

It seems that installation of it is success. But, using a follow simple source code, segmentation fault occurs.
```C
// a.c
#include <stdio.h>
#include <omp.h>

int main(void) {
  int isHost = -1;

#pragma omp target map(from: isHost)
  { isHost = omp_is_initial_device(); }

  if(isHost < 0)
    printf("Runtime error, isHost=%d\n", isHost);

  printf("Target region executed on the %s\n", isHost ? "host" : "device");

  return isHost;
}
```

> $ clang  -O3  -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda a.c
> $ ./a.out
> zsh: segmentation fault  ./a.out

Thanks,

**Comment by siddharth19** [comment]
I also got the same problem. Using the device clause in the target directive resolves the problem.

**Comment by mnakao** [comment]
@siddharth19 Thanks ! "segmentation fault" does not occur. But, the target construct of the above program executes in host.

To see if the compiler is aware of the GPU,  I add the following line into the code.

> printf("%d\n", omp_get_num_devices());

The return value is "0".
I have confirmed that the CUDA sample programs run on the GPU in my environment.

What's wrong ?

**Comment by gr409** [comment]
I haven't been able to reproduce either problem. I get no segfaults and the target region runs on the device. I suspect there is some problem with your system configuration. E.g. is the driver running correctly or is the GPU responding?

**Comment by siddharth19** [comment]
@mnakao I also get the return value as 0. However, when I use device(0) as the clause to target directive it does offload to the the GPU. I have verified it using the NVIDIA Profiler. Giving device(1) as a clause runs it on the host.
@gr409 I have been trying to figure out a reason for the same.

**Comment by gr409** [comment]
> However, when I use device(0) as the clause to target directive it does offload to the the GPU. I have verified it using the NVIDIA Profiler. Giving device(1) as a clause runs it on the host.

If the system has only 1 device, then that's device no. 0. If you give `device(1)`, then this device does not exist and execution falls back on the host.

**Comment by mnakao** [comment]
@gr409 Thanks for your comment. I try to execute CUDA some programs, they run successful. And I write an OpenACC program, it also run successful. Thus, I think that my system configuration is OK.

In the OpenACC program, I use a function acc_get_num_devices(acc_device_nvidia) to return number of devices.  The return value is "2", which is correct.

**Comment by mnakao** [comment]
@gr409 Thanks again. I execute my program with nvprof. In my program, target clause is added.

```C
#pragma omp target map(from: isHost) device(0)
  { isHost = omp_is_initial_device(); }
```

> $ clang -O3 -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda a.c
> $ nvprof ./a.out

However,  nvprof does not output anything.
I also try to execute other programs (CUDA, OpenACC) with nvprof. The nvprof outputs profiling results.

Is clang-ykt not generating a binary for GPU?

**Comment by mnakao** [comment]
@siddharth19 @gr409 I solved this issue.

The wiki describes that libelf1 is required for the clang-ykt.
https://github.com/clang-ykt/clang/wiki

But the clang-ykt also requires libelf-dev in my environment (Debian 9.4, the latest).

When installing the clang-ykt before installing libelf-dev, following message is output.

> $ ninja install
> :
> -- Could NOT find LIBOMPTARGET_DEP_LIBELF (missing:  LIBOMPTARGET_DEP_LIBELF_LIBRARIES LIBOMPTARGET_DEP_LIBELF_INCLUDE_DIRS)
> -- LIBOMPTARGET: Building offloading runtime library libomptarget.
> -- LIBOMPTARGET: Not building aarch64 offloading plugin: machine not found in the system.
> -- LIBOMPTARGET: Not building CUDA offloading plugin: libelf dependency not found.

After install libelf-dev, I can compile and execute my source code.

Thanks,

**Comment by ruixueqingyang** [comment]
Hi, I installed libelf-dev. But segmentation fault still occurs.

the source code I used:
`// a.c
#include <stdio.h>
#include <omp.h>

int main(void) {
  int isHost = -1;

#pragma omp target map(from: isHost)
  { isHost = omp_is_initial_device(); }

  if(isHost < 0)
    printf("Runtime error, isHost=%d\n", isHost);

  printf("Target region executed on the %s\n", isHost ? "host" : "device");

  return isHost;
}`

the compiler command I used:
`clang -O3 -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda -v a.c`

the compiling information I got:
`wfr@parallelgroup:~/work/test_offloading_compiler$ clang -O3 -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda -v a.c
clang version 4.0.0 (https://github.com/clang-ykt/clang 49d8020e03f898ea31212f6c565001e067f67d4f) (https://github.com/clang-ykt/llvm aa08e5a3c3670cd86fb4bee034a7626bb26ad57e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/wfr/opt/ibm/clang-ykt/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda-9.1, version 9.1
 "/home/wfr/opt/ibm/clang-ykt/bin/clang-4.0" -cc1 -triple x86_64-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -disable-llvm-verifier -discard-value-names -main-file-name a.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -v -dwarf-column-info -debugger-tuning=gdb -resource-dir /home/wfr/opt/ibm/clang-ykt/bin/../lib/clang/4.0.0 -internal-isystem /usr/local/include -internal-isystem /home/wfr/opt/ibm/clang-ykt/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /usr/local/include -internal-isystem /home/wfr/opt/ibm/clang-ykt/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -fdebug-compilation-dir /home/wfr/work/test_offloading_compiler -ferror-limit 19 -fmessage-length 183 -fopenmp -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /tmp/a-d17460.bc -x c a.c -fopenmp-targets=nvptx64-nvidia-cuda
clang -cc1 version 4.0.0 based upon LLVM 4.0.0svn default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/home/wfr/opt/ibm/clang-ykt/bin/../lib/clang/4.0.0/include"
ignoring duplicate directory "/usr/include/x86_64-linux-gnu"
ignoring duplicate directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /home/wfr/opt/ibm/clang-ykt/bin/../lib/clang/4.0.0/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
 "/home/wfr/opt/ibm/clang-ykt/bin/clang-4.0" -cc1 -triple nvptx64-nvidia-cuda -aux-triple x86_64-unknown-linux-gnu -S -disable-free -disable-llvm-verifier -discard-value-names -main-file-name a.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fmath-errno -no-integrated-as -fuse-init-array -mlink-cuda-bitcode /usr/local/cuda-9.1/nvvm/libdevice/libdevice.10.bc -target-feature +ptx60 -mlink-cuda-bitcode /home/wfr/opt/ibm/clang-ykt/lib/libomptarget-nvptx-35.bc -target-cpu sm_35 -v -v -dwarf-column-info -debugger-tuning=cuda-gdb -resource-dir /home/wfr/opt/ibm/clang-ykt/bin/../lib/clang/4.0.0 -internal-isystem /usr/local/include -internal-isystem /home/wfr/opt/ibm/clang-ykt/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /usr/local/include -internal-isystem /home/wfr/opt/ibm/clang-ykt/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -fno-dwarf-directory-asm -fdebug-compilation-dir /home/wfr/work/test_offloading_compiler -ferror-limit 19 -fmessage-length 183 -fopenmp -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /tmp/a-1a3d5d.s -x c a.c -fopenmp-is-device -fopenmp-host-ir-file-path /tmp/a-d17460.bc
clang -cc1 version 4.0.0 based upon LLVM 4.0.0svn default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/home/wfr/opt/ibm/clang-ykt/bin/../lib/clang/4.0.0/include"
ignoring duplicate directory "/usr/include/x86_64-linux-gnu"
ignoring duplicate directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /home/wfr/opt/ibm/clang-ykt/bin/../lib/clang/4.0.0/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
 "/usr/local/cuda-9.1/bin/ptxas" -m64 -O3 -v --gpu-name sm_35 --output-file /tmp/a-af689a.o /tmp/a-1a3d5d.s -c
ptxas info    : 12 bytes gmem
ptxas info    : Compiling entry function '__omp_offloading_827_2a2355_main_l8' for 'sm_35'
ptxas info    : Function properties for __omp_offloading_827_2a2355_main_l8
    8 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 10 registers, 336 bytes cmem[0]
 "/bin/cp" /tmp/a-af689a.o /tmp/a-af689a-35f141.cubin
 "/usr/local/cuda-9.1/bin/nvcc" -dlink -cubin -o /tmp/a-507839.out -v -arch sm_35 -L/home/wfr/opt/ibm/clang-ykt/lib -L/home/wfr/opt/ibm/clang-ykt/lib -L/usr/local/cuda-9.1/lib64 -L. -L/home/wfr/opt/ibm/clang-ykt/lib -lomptarget-nvptx /tmp/a-af689a-35f141.cubin
#$ _SPACE_= 
#$ _CUDART_=cudart
#$ _HERE_=/usr/local/cuda-9.1/bin
#$ _THERE_=/usr/local/cuda-9.1/bin
#$ _TARGET_SIZE_=
#$ _TARGET_DIR_=
#$ _TARGET_SIZE_=64
#$ TOP=/usr/local/cuda-9.1/bin/..
#$ NVVMIR_LIBRARY_DIR=/usr/local/cuda-9.1/bin/../nvvm/libdevice
#$ LD_LIBRARY_PATH=/usr/local/cuda-9.1/bin/../lib:/home/wfr/opt/ibm/clang-ykt/lib:/home/wfr/opt/ibm/clang-ykt/lib:/usr/local/cuda-9.1/lib64:
#$ PATH=/usr/local/cuda-9.1/bin/../nvvm/bin:/usr/local/cuda-9.1/bin:/home/wfr/opt/ibm/clang-ykt/bin:/home/wfr/opt/ibm/clang-ykt/bin:/home/wfr/bin:/home/wfr/.local/bin:/usr/java/jdk1.8.0_171/bin:/usr/java/jdk1.8.0_171/jre/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda-9.1/bin
#$ INCLUDES="-I/usr/local/cuda-9.1/bin/..//include"  
#$ LIBRARIES=  "-L/usr/local/cuda-9.1/bin/..//lib64/stubs" "-L/usr/local/cuda-9.1/bin/..//lib64"
#$ CUDAFE_FLAGS=
#$ PTXAS_FLAGS=
#$ fatbinary --create="/tmp/tmpxft_000111dd_00000000-2_a-af689a-35f141.fatbin" -64 --cmdline="--compile-only  " "--image=profile=sm_35,file=/tmp/a-af689a-35f141.cubin" --embedded-fatbin="/tmp/tmpxft_000111dd_00000000-2_a-af689a-35f141.fatbin.c"  --device-c
#$ rm /tmp/tmpxft_000111dd_00000000-2_a-af689a-35f141.fatbin
#$ gcc -c -x c++ -DFATBINFILE="\"/tmp/tmpxft_000111dd_00000000-2_a-af689a-35f141.fatbin.c\"" -I. -D__NV_MODULE_ID="_tmp_tmpxft_000111dd_00000000_5_a_af689a_35f141_o" "-I/usr/local/cuda-9.1/bin/..//include"   -D"__CUDACC_VER_BUILD__=85" -D"__CUDACC_VER_MINOR__=1" -D"__CUDACC_VER_MAJOR__=9" -m64 -o "/tmp/tmpxft_000111dd_00000000-5_a-af689a-35f141.o" "/usr/local/cuda-9.1/bin/crt/prelink.stub" 
#$ nvlink --arch=sm_35 -m64 -L"/home/wfr/opt/ibm/clang-ykt/lib" -L"/home/wfr/opt/ibm/clang-ykt/lib" -L"/usr/local/cuda-9.1/lib64" -L"." -L"/home/wfr/opt/ibm/clang-ykt/lib" -lomptarget-nvptx   "-L/usr/local/cuda-9.1/bin/..//lib64/stubs" "-L/usr/local/cuda-9.1/bin/..//lib64" -cpu-arch=X86_64 "/tmp/tmpxft_000111dd_00000000-5_a-af689a-35f141.o"  -lcudadevrt  -o "/tmp/a-507839.out"
 "/home/wfr/opt/ibm/clang-ykt/bin/clang-4.0" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name a.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -v -dwarf-column-info -debugger-tuning=gdb -resource-dir /home/wfr/opt/ibm/clang-ykt/bin/../lib/clang/4.0.0 -O3 -fdebug-compilation-dir /home/wfr/work/test_offloading_compiler -ferror-limit 19 -fmessage-length 183 -fopenmp -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /tmp/a-d12468.o -x ir /tmp/a-d17460.bc
clang -cc1 version 4.0.0 based upon LLVM 4.0.0svn default target x86_64-unknown-linux-gnu
 "/usr/bin/ld" -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/5.4.0/crtbegin.o -L/usr/lib/gcc/x86_64-linux-gnu/5.4.0 -L/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../.. -L/home/wfr/opt/ibm/clang-ykt/bin/../lib -L/lib -L/usr/lib /tmp/a-d12468.o -L/home/wfr/opt/ibm/clang-ykt/lib -L/home/wfr/opt/ibm/clang-ykt/lib -L/usr/local/cuda-9.1/lib64 -L. -lomp -lomptarget -lgcc --as-needed -lgcc_s --no-as-needed -lpthread -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/5.4.0/crtend.o /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu/crtn.o -T /tmp/a-472748.lk
wfr@parallelgroup:~/work/test_offloading_compiler$ ./a.out 
Segmentation fault (core dumped)`
