### ISSUE TITLE
nvptx64-nvidia-cuda - no available targets on PPC64le RHEL 7.2

### ISSUE THREAD

**Issue by reguly** [clang-ykt/clang#8]
Having compiled clang with OMP offload support, with the following cmake command:
cmake -DCMAKE_BUILD_TYPE=DEBUG -DLLVM_TARGETS_TO_BUILD="NVPTX" -DCMAKE_INSTALL_PREFIX="/home/ireguly/forge/clang_4/compiler" \ -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_BACKTRACES=ON  -DLLVM_ENABLE_WERROR=OFF -DBUILD_SHARED_LIBS=OFF -DLLVM_ENABLE_RTTI=ON -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DLIBOMPTARGET_NVPTX_ENABLE_BCLIB=true -DLIBOMPTARGET_NVPTX_CUDA_COMPILER=clang -DLIBOMPTARGET_NVPTX_BC_LINKER=llvm-link   -DCMAKE_C_FLAGS="'-DOPENMP_NVPTX_COMPUTE_CAPABILITY=37'" -DCMAKE_CXX_FLAGS="'-DOPENMP_NVPTX_COMPUTE_CAPABILITY=37'" -DLIBOMPTARGET_NVPTX_COMPUTE_CAPABILITY=37  ..

Some configure details that might be relevant:
-- Targeting NVPTX
-- Could NOT find LIBOMPTARGET_DEP_LIBELF (missing:  LIBOMPTARGET_DEP_LIBELF_INCLUDE_DIRS)
-- Could NOT find LIBOMPTARGET_DEP_LIBFFI (missing:  LIBOMPTARGET_DEP_LIBFFI_LIBRARIES LIBOMPTARGET_DEP_LIBFFI_INCLUDE_DIRS)
-- LIBOMPTARGET: Building offloading runtime library libomptarget.
-- LIBOMPTARGET: Not building CUDA offloading plugin: libelf dependency not found.
-- LIBOMPTARGET: Not building PPC64 offloading plugin: machine not found in the system.
-- LIBOMPTARGET: Not building PPC64le offloading plugin: libelf dependency not found.
-- LIBOMPTARGET: Not building x86_64 offloading plugin: machine not found in the system.
-- LIBOMPTARGET: Building CUDA offloading device RTL.
-- LIBOMPTARGET: Building CUDA LLVM bitcode offloading device RTL.

When actually trying to use the compiler, I am getting the following error:
clang -O3  -fopenmp=libomp -fopenmp-targets=nvptx64-nvidia-cuda  example.c
error: unable to create target: 'No available targets are compatible with this triple.'

With -v:
-bash-4.2$ clang -O3 -I/home/ireguly/forge/clang_4/llvm/build/projects/openmp/runtime/src/ -fopenmp=libomp -fopenmp-targets=nvptx64-nvidia-cuda -fopenmp-nonaliased-maps -ffp-contract=fast example.c -v
clang version 4.0.0
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
InstalledDir: /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/lib/../bin
Found candidate GCC installation: /usr/lib/gcc/ppc64le-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/ppc64le-redhat-linux/4.8.5
Selected GCC installation: /usr/lib/gcc/ppc64le-redhat-linux/4.8.5
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda, version 7.5
 "/gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/clang-4.0" -cc1 -triple powerpc64le-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -main-file-name example.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -ffp-contract=fast -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu ppc64le -mfloat-abi hard -target-abi elfv2 -v -dwarf-column-info -debugger-tuning=gdb -resource-dir /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/../lib/clang/4.0.0 -I /home/ireguly/forge/clang_4/llvm/build/projects/openmp/runtime/src/ -internal-isystem /usr/local/include -internal-isystem /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/../lib/clang/4.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /usr/local/include -internal-isystem /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/../lib/clang/4.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -fdebug-compilation-dir /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09 -ferror-limit 19 -fmessage-length 141 -fopenmp -fopenmp-nonaliased-maps -fno-signed-char -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /tmp/example-06cb3a.bc -x c example.c -fopenmp-targets=nvptx64-nvidia-cuda
clang -cc1 version 4.0.0 based upon LLVM 4.0.0svn default target powerpc64le-unknown-linux-gnu
ignoring nonexistent directory "/home/ireguly/forge/clang_4/llvm/build/projects/openmp/runtime/src/"
ignoring nonexistent directory "/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/../lib/clang/4.0.0/include"
ignoring duplicate directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/../lib/clang/4.0.0/include
 /usr/include
End of search list.
 "/gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/clang-4.0" -cc1 -triple nvptx64-nvidia-cuda -aux-triple powerpc64le-unknown-linux-gnu -S -disable-free -main-file-name example.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -ffp-contract=fast -no-integrated-as -mlink-cuda-bitcode /usr/local/cuda/nvvm/libdevice/libdevice.compute_35.10.bc -target-feature +ptx42 -mlink-cuda-bitcode /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/lib/libomptarget-nvptx.bc -target-cpu sm_37 -v -dwarf-column-info -debugger-tuning=gdb -resource-dir /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/../lib/clang/4.0.0 -I /home/ireguly/forge/clang_4/llvm/build/projects/openmp/runtime/src/ -internal-isystem /usr/local/include -internal-isystem /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/../lib/clang/4.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /usr/local/include -internal-isystem /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/../lib/clang/4.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -fno-dwarf-directory-asm -fdebug-compilation-dir /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09 -ferror-limit 19 -fmessage-length 141 -fopenmp -fopenmp-nonaliased-maps -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /tmp/example-f42879.s -x c example.c -fopenmp-is-device -fopenmp-host-ir-file-path /tmp/example-06cb3a.bc
clang -cc1 version 4.0.0 based upon LLVM 4.0.0svn default target powerpc64le-unknown-linux-gnu
ignoring nonexistent directory "/home/ireguly/forge/clang_4/llvm/build/projects/openmp/runtime/src/"
ignoring nonexistent directory "/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/../lib/clang/4.0.0/include"
ignoring duplicate directory "/usr/include"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/../lib/clang/4.0.0/include"
ignoring duplicate directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/../lib/clang/4.0.0/include
 /usr/include
End of search list.
 "/usr/local/cuda/bin/ptxas" -m64 -O3 -v --gpu-name sm_37 --output-file /tmp/example-e47c36.o /tmp/example-f42879.s -c
ptxas info    : 260833282 bytes gmem
ptxas info    : Compiling entry function '__omp_offloading_fd00_d6ef291_saxpy_l20' for 'sm_37'
ptxas info    : Function properties for __omp_offloading_fd00_d6ef291_saxpy_l20
    8 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 33 registers, 368 bytes cmem[0], 12 bytes cmem[2]
ptxas info    : Function properties for __omp_offloading_fd00_d6ef291_saxpy_l20_worker
    96 bytes stack frame, 92 bytes spill stores, 92 bytes spill loads
ptxas info    : Compiling entry function '__omp_offloading_fd00_d6ef291_main_l69' for 'sm_37'
ptxas info    : Function properties for __omp_offloading_fd00_d6ef291_main_l69
    8 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 33 registers, 376 bytes cmem[0], 12 bytes cmem[2]
ptxas info    : Function properties for __omp_offloading_fd00_d6ef291_main_l69_worker
    96 bytes stack frame, 92 bytes spill stores, 92 bytes spill loads
ptxas info    : Function properties for _$_omp_outlined_$__wrapper
    72 bytes stack frame, 68 bytes spill stores, 68 bytes spill loads
ptxas info    : Function properties for _$_omp_outlined_$__$_1_wrapper
    72 bytes stack frame, 68 bytes spill stores, 68 bytes spill loads
 "/..//bin/cp" /tmp/example-e47c36.o /tmp/example-e47c36-64552f.cubin
 "/usr/local/cuda/bin/nvlink" -o /tmp/example-847645.out -v -arch sm_37 -lomptarget-nvptx /tmp/example-e47c36-64552f.cubin -L/gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/lib
nvlink info    : Function '_$_omp_outlined_$__$_1_wrapper' has address taken but no possible call to it
nvlink info    : Function '_$_omp_outlined_$__wrapper' has address taken but no possible call to it
nvlink info    : 348887990 bytes gmem
nvlink info    : Function properties for '__omp_offloading_fd00_d6ef291_main_l69':
nvlink info    : used 46 registers, 104 stack, 913 bytes smem, 376 bytes cmem[0], 48 bytes cmem[2], 0 bytes lmem
nvlink info    : Function properties for '__omp_offloading_fd00_d6ef291_saxpy_l20':
nvlink info    : used 46 registers, 104 stack, 913 bytes smem, 368 bytes cmem[0], 48 bytes cmem[2], 0 bytes lmem
 "/gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/clang-4.0" -cc1 -triple powerpc64le-unknown-linux-gnu -emit-obj -disable-free -main-file-name example.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -ffp-contract=fast -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu ppc64le -mfloat-abi hard -target-abi elfv2 -v -dwarf-column-info -debugger-tuning=gdb -resource-dir /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09/llvm-master/build2/bin/../lib/clang/4.0.0 -O3 -fdebug-compilation-dir /gpfs/fairthorpe/local/HCP110/mxs09/ixr17-mxs09 -ferror-limit 19 -fmessage-length 141 -fopenmp -fopenmp-nonaliased-maps -fno-signed-char -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /tmp/example-e25ad8.o -x ir /tmp/example-06cb3a.bc
clang -cc1 version 4.0.0 based upon LLVM 4.0.0svn default target powerpc64le-unknown-linux-gnu
error: unable to create target: 'No available targets are compatible with this triple.'
1 error generated.

**Comment by sfantao** [comment]
The compiler doesn't have a backend for the host. You need to select the host in the macro -DLLVM_TARGETS_TO_BUILD="NVPTX": usually "NVPTX,PowerPC".

You also need to install libelf-dev in your system.

Thanks,
Samuel

**Comment by reguly** [comment]
That does seem to resolve the issue, thank you.
